APP:
  NAME: technopartner
  ENV: development
  URL: https://staging-app.co.id
  PORT: 8004

ROUTE:
  METHODS: [GET, POST, PUT, DELETE]
  HEADERS: [Content-Type, Authorization, Authorization-ID, Accept-Key]
  ORIGIN: ['*']

DATABASE:
  READ:
    USERNAME: postgres
    PASSWORD: junior34
    URL: localhost
    PORT: 5432
    DB_NAME: technopartner_finance
    MAXIDLECONNS: 5
    MAXOPENCONNS: 5
    MAXLIFETIME: 31
    TIMEOUT: 100
    SSL_MODE: disable
  WRITE:
    USERNAME: postgres
    PASSWORD: junior34
    URL: localhost
    PORT: 5432
    DB_NAME: technopartner_finance
    MAXIDLECONNS: 5
    MAXOPENCONNS: 5
    MAXLIFETIME: 31
    TIMEOUT: 100
    SSL_MODE: disable

AUTHORIZATION:
  JWT:
    IS_ACTIVE: true
    ACCESS_TOKEN_SECRET_KEY: 11JGC$K7VL6TOvt!
    ACCESS_TOKEN_DURATION: 120

KEY:
  USER: Gd4*!xW8$MkZfYw#12Hb5DJ@pUQjvzOB